### PR TITLE
Add a changelog

### PR DESCRIPTION
**Pull request by chocolateboy**
Automatically generated by [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) with the command:

    $ changelog --header-label "# Changelog" --token <token> citizen428/methodfinder

Tags, labels and a milestone have been added to the repo to improve its output (and improve the repo :-).

The [changelog](https://github.com/citizen428/methodfinder/blob/add-changelog/CHANGELOG.md) can easily be generated by a [Rake task](https://github.com/github-changelog-generator/github-changelog-generator#rake-task), and the "Thanks" section can be removed from the README if it's merged  (since contributors are credited in the changelog), but I'll hold off on those proposals until the dust has settled on #16.

### CODE REVIEW

**Comment by citizen428** [comment]
I'll remove the "Thanks" section in #16, so you can go ahead and add the Changelog generator as a dev dependency, configure the Rake task and run it automatically when we build the gem or something (I'll just forget otherwise).

**Comment by citizen428** [comment]
I rebased this against current `master` and updated the `README`, so you're good to go now.

**Comment by chocolateboy** [comment]
I've rebased this again and added:

* some missing fixes from #16 
* a rake task to generate the changelog (`changelog`)
* a rake task to run the tests and generate the changelog (`prerelease`)

The `changelog` tasks are separate (rather then e.g. attached to `release`) because the `release` task requires the repo to be up-to-date. Also, generating the changelog hits the GitHub API, which is rate limited.

**Comment by citizen428** [comment]
Hm, strange. I did some of it at the office, must have forgotten to actually push or more likely: typed `git push`, didn't come back to check and it had timed out when waiting for the passphrase for my SSH key (I probably hadn't done an `ssh-add` yet). Sorry for the inconvenience and thanks for fixing it!

**Comment by citizen428** [comment]
Good to go and wow, does that gem have a lot of dependencies.

**Pull request merged**
